### ISSUE TITLE
demographic variables

### ISSUE THREAD

**Issue by szorowi1** [nivlab/nivturk-templates#13]
- [x] add self-reported years of education
- [x] remove english language questions?

**Comment by szorowi1** [comment]
@danielbrianbennett, any additional demographic variables you'd like to be added to the default demographics plugin?

**Comment by danielbrianbennett** [comment]
Thanks for adding this. How about country of residence? This is going to be something that comes up for me as I try to recruit samples from outside North America!

**Comment by szorowi1** [comment]
Actually this raises an interesting question: is our demographics plugin too US-centric? I'm thinking specifically of our ethnicity variables, which come from the NIH. Do these need to be adjusted for an Australian context?

**Comment by danielbrianbennett** [comment]
Yeah, that is an interesting question. I think those categories should stay in the default plugin because for NIH-funded research, those are the demographic lines that participants have be broken down along in reporting. I'm going to use something different for my stuff here in Australia -- I will probably drop the race/ethnicity questions entirely, since my funders don't require me to report them and I don't feel comfortable using those variables in any analysis I can think of -- but I can just make that change in my own code

**Comment by szorowi1** [comment]
In that case I may leave out the nationality question given that the demographic items are already aimed at US-centric participant. Is that reasonable?

**Comment by danielbrianbennett** [comment]
Sure, seems reasonable to me.

**Comment by szorowi1** [comment]
I've added a (US-centric) education question to the demographics form. For posterity's sake, the categorical levels were chosen based on reports/analyses from the National Center for Educational Statistics and the US Census Bureau's Current Population Survey:

- https://nces.ed.gov/programs/coe/indicator_caa.asp
- https://www2.census.gov/programs-surveys/cps/techdocs/questionnaires/Demographics.pdf (page 11)

While we're making modifications, how would we feel about removing the English language questions ("is English your first language?" "How well do you speak English?")? While I understand my original motivations for including these, the lack of variation in responses to both items has meant that I've never actually used these items in any analysis. Ok to remove, do you think?
